# Generated by Django 4.0.2 on 2022-03-10 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_category_order_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Cat',
        ),
    ]
