# Generated by Django 4.0.2 on 2022-03-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_product_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cat',
            new_name='Tag',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Personal', 'Personal'), ('School', 'School')], max_length=200, null=True),
        ),
    ]
